# Workflow for deploying a Next.js project to GitHub Pages
name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: ['migrate-to-nextjs']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          npm run export

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'out'  # Adjusted to the 'out' directory for Next.js export

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
